services:
  autoweb:
    container_name: autoweb
    image: forge.localtoast.xyz/bredo/autoweb:latest
    environment:
      GIT_REPOSITORY: ""
    ports:
      - "3000:3000"
    restart: on-failure:5
